### ISSUE TITLE
PlatformException(error, null, null, java.lang.NullPointerException)

### ISSUE THREAD

**Issue by sungyoun1223** [juliansteenbakker/flutter_ble_peripheral#172]
**I am using flutter_ble_peripheral in flutter_foreground_task. It worked 1.1.1, but I have the following problem since 1.2.0.**

I think The same issue is also occurring when using `activityBinding!!`
There was a function that used activityBinding!! in 1.1.1, but there was no problem using `start()`,`stop()`,`isAdvertising`.

E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): Failed to handle method call E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): java.lang.NullPointerException E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralPlugin.checkBluetoothState(FlutterBlePeripheralPlugin.kt:77) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralPlugin.onMethodCall(FlutterBlePeripheralPlugin.kt:98) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at android.os.Handler.handleCallback(Handler.java:942) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at android.os.Handler.dispatchMessage(Handler.java:99) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at android.os.Looper.loopOnce(Looper.java:226) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at android.os.Looper.loop(Looper.java:313) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at android.app.ActivityThread.main(ActivityThread.java:8757) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at java.lang.reflect.Method.invoke(Native Method) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state(23104): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by juliansteenbakker** [comment]
It's been a while, but i have released a new version of this package, [v3.0.0](https://github.com/juliansteenbakker/flutter_ble_peripheral/releases/tag/v3.0.0), together with the other side of it, [flutter_ble_central](https://github.com/juliansteenbakker/flutter_ble_central/releases/tag/v1.0.0) v1.0.0. The bluetooth state check no longer needs an activity, so this NPE should be gone. Calling `start()` from a service still needs one, i am tracking that in #237.

Please check again with these versions, and reopen if it's still there.
