### ISSUE TITLE
Failed to handle method call && dvertising data too big

### ISSUE THREAD

**Issue by runoob-coder** [juliansteenbakker/flutter_ble_peripheral#206]
i cannot start advertusung on Android：

![Screenshot_20241021-222122](https://github.com/user-attachments/assets/daa8f50e-77d3-4500-8e97-0de0d381d469)

D/BluetoothAdapter( 3356): isLeEnabled(): ON
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): Failed to handle method call
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): java.lang.IllegalArgumentException: Advertising data too big
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at android.bluetooth.le.BluetoothLeAdvertiser.startAdvertisingSet(BluetoothLeAdvertiser.java:379)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at android.bluetooth.le.BluetoothLeAdvertiser.startAdvertisingSet(BluetoothLeAdvertiser.java:309)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralManager.startSet(FlutterBlePeripheralManager.kt:197)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralPlugin.startPeripheral(FlutterBlePeripheralPlugin.kt:260)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralPlugin.onMethodCall(FlutterBlePeripheralPlugin.kt:106)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at android.os.Handler.handleCallback(Handler.java:793)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at android.os.Looper.loop(Looper.java:164)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at android.app.ActivityThread.main(ActivityThread.java:6496)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#dev.steenbakker.flutter_ble_peripheral/ble_state( 3356): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter ( 3356): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Advertising data too big, null, java.lang.IllegalArgumentException: Advertising data too big
E/flutter ( 3356): 	at android.bluetooth.le.BluetoothLeAdvertiser.startAdvertisingSet(BluetoothLeAdvertiser.java:379)
E/flutter ( 3356): 	at android.bluetooth.le.BluetoothLeAdvertiser.startAdvertisingSet(BluetoothLeAdvertiser.java:309)
E/flutter ( 3356): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralManager.startSet(FlutterBlePeripheralManager.kt:197)
E/flutter ( 3356): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralPlugin.startPeripheral(FlutterBlePeripheralPlugin.kt:260)
E/flutter ( 3356): 	at dev.steenbakker.flutter_ble_peripheral.FlutterBlePeripheralPlugin.onMethodCall(FlutterBlePeripheralPlugin.kt:106)
E/flutter ( 3356): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 3356): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 3356): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 3356): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 3356): 	at android.os.Handler.handleCallback(Handler.java:793)
E/flutter ( 3356): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 3356): 	at android.os.Looper.loop(Looper.java:164)
E/flutter ( 3356): 	at android.app.ActivityThread.main(ActivityThread.java:6496)
E/flutter ( 3356): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3356): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/flutter ( 3356): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter ( 3356): )
E/flutter ( 3356): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 3356): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 3356): <asynchronous suspension>
E/flutter ( 3356): #2      FlutterBlePeripheral.start (package:flutter_ble_peripheral/src/flutter_ble_peripheral.dart:100:9)
E/flutter ( 3356): <asynchronous suspension>
E/flutter ( 3356): #3      FlutterBlePeripheralExampleState.build.<anonymous closure> (package:eboard_displayer/peripheral/main.dart:163:19)
E/flutter ( 3356): <asynchronous suspension>
E/flutter ( 3356): 
D/Region  ( 3356):   Region surface:queuebuffer (this=0x920536e0, count=1)
D/Region  ( 3356):     [  0,   0,   0,   0]
D/Region  ( 3356):   Region surface:queuebuffer (this=0x920536e0, count=1)
D/Region  ( 3356):     [  0,   0,   0,   0]
D/Region  ( 3356):   Region surface:queuebuffer (this=0x920536e0, count=1)
D/Region  ( 3356):     [  0,   0,   0,   0]
D/Region  ( 3356):   Region surface:queuebuffer (this=0x920536e0, count=1)
D/Region  ( 3356):     [  0,   0,   0,   0]

**Comment by juliansteenbakker** [comment]
It's been a while, but i have released a new version of this package, [v3.0.0](https://github.com/juliansteenbakker/flutter_ble_peripheral/releases/tag/v3.0.0), together with the other side of it, [flutter_ble_central](https://github.com/juliansteenbakker/flutter_ble_central/releases/tag/v1.0.0) v1.0.0. "Advertising data too big" is the BLE payload limit, so you will have to trim what you put in the advertisement. 3.0.0 does make the choice explicit: `AndroidAdvertiseSettings.advertiseSetParameters` selects the extended advertising api, which gives you more room.

Please check again with these versions, and reopen if it's still there.
